#!/bin/sh

UPDATE_BRANCH=$(uci get autoupdater.settings.branch)

if [ "$UPDATE_BRANCH" = "nightly" ] || [ "$UPDATE_BRANCH" = "experimental" ]; then
    # migrate eol nodes in the nightly and testing branch for now to beta
    uci set autoupdater.settings.branch='beta'
fi
